[client]
showSidebarNavigation = false

[server]
maxUploadSize = 200

[theme]
base = "dark"
primaryColor = "#3B82F6"
backgroundColor = "#0B1020"
secondaryBackgroundColor = "#111827"
textColor = "#F9FAFB"
